-- Users table is handled by Supabase Auth, but we can add a trigger to create a profile if needed.
-- For now, we rely on user_metadata or a profiles table.

-- 1. ADDRESSES TABLE
create table public.addresses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  label text not null, -- e.g. "Home", "Work"
  address_text text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. ORDERS TABLE
create table public.orders (
  id text primary key, -- We use the "VK-2026-..." string as ID
  user_id uuid references auth.users not null,
  total numeric not null,
  status text default 'Processing' check (status in ('Processing', 'Shipped', 'Out for Delivery', 'Delivered', 'Cancelled')),
  shipping_address text not null,
  payment_method text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ORDER ITEMS TABLE
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id text references public.orders(id) on delete cascade not null,
  product_id integer not null, -- From DummyJSON
  title text not null,
  price numeric not null,
  quantity integer not null,
  thumbnail text,
  category text
);

-- 4. ENABLE RLS (Row Level Security) - Crucial for Safety
alter table public.addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- 5. CREATE POLICIES (Allow users to see only their own data)

-- Addresses
create policy "Users can view their own addresses" 
on public.addresses for select 
using (auth.uid() = user_id);

create policy "Users can insert their own addresses" 
on public.addresses for insert 
with check (auth.uid() = user_id);

create policy "Users can delete their own addresses" 
on public.addresses for delete 
using (auth.uid() = user_id);

-- Orders
create policy "Users can view their own orders" 
on public.orders for select 
using (auth.uid() = user_id);

create policy "Users can insert their own orders" 
on public.orders for insert 
with check (auth.uid() = user_id);

-- Order Items
create policy "Users can view their own order items" 
on public.order_items for select 
using ( auth.uid() = (select user_id from public.orders where id = order_items.order_id) );

create policy "Users can insert their own order items" 
on public.order_items for insert 
with check ( auth.uid() = (select user_id from public.orders where id = order_items.order_id) );
