-- PRODUCTS TABLE
create table public.products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  category text not null,
  thumbnail text, -- URL or Base64
  seller_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table public.products enable row level security;

-- Policies
create policy "Public can view all products" 
on public.products for select 
using (true);

create policy "Sellers can insert products" 
on public.products for insert 
with check (auth.uid() = seller_id);

-- (Optional) If you want sellers to edit their own:
create policy "Sellers can update their own products" 
on public.products for update
using (auth.uid() = seller_id);
